version: "3"

services:
  nordvpn:
    build: ./nordvpn
    image: 'dockerhub.zolotous.com/nordvpn-alpine:v.0.0.1'
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - USER=dreaxy11@gmail.com
      - PASS=warcraft12
      - CONNECT=United_States
      - NETWORK=192.168.88.0/24
#    command: ping localhost

  test:
    image: alpine:3.10
    network_mode: service:nordvpn
    depends_on:
      - nordvpn
    command: /bin/sh -c "sleep 60 && ping zolotous.com"



